### ISSUE TITLE
papermill & batch integration/compatibility?

### ISSUE THREAD

**Issue by AndrewAnnex** [neptune-ai/neptune-notebooks#164]
For my work, I run experiments as batch jobs on a HPC cluster using papermill (https://papermill.readthedocs.io/en/latest/) to execute ipython/jupyter notebooks, inside the notebooks I use the neptune client to upload metrics and artifacts. 

I would also like the output notebooks from papermill to be usable within the neptune website ui, and to automatically log the checkpoints and such so I can remotely monitor a job or review the notebook after the job has completed without needing to ssh into the cluster again. 

I haven't updated to the newer neptune api client yet, or to newer versions of this project, but is it possible currently to use the notebook plugin to automatically upload the notebooks in a batch-mode manner? I looked at the docs and there maybe a mechanism to use the CLI inside/outside the notebook to do this, but there appears to be a focus on the "interactive" use case when a user is using jupyter/jupyter lab inside a browser and has access to the UI.

 Currently I am going to try a work-around that just uploads the notebook using `log_artifact` from the legacy API in the last cell of the notebook, but that is not a great solution as the neptune website likely won't render the notebook in the browser. 

Ideally, I would like either this plugin or the neptune client to know (or be provided a path to) a notebook during runtime and not need to worry about anything else, it just isn't clear from the docs if that is the case now with the newer versions of the client and this project, or not.

**Comment by PiotrJander** [comment]
Hi @AndrewAnnex , I understand you would like to programmatically upload notebooks to Neptune. Here's how to do it:

Install `neptune-notebooks`

```
pip install neptune-notebooks
```

(2) Export your Neptune API token:

```
export NEPTUNE_API_TOKEN="YOUR_TOKEN"
```

(3) Upload your notebook:

```
import neptune_notebooks.sync
neptune_notebooks.sync.sync('<workspace>/<project>', '<path-to-your-notebook>')
```

This will create a new notebook in the project or a new checkpoint of an existing project.

That's it. It should work with both new-style and old-style projects.

Let us know if it helps!

**Comment by AndrewAnnex** [comment]
Thanks @PiotrJander for the tips, I tried the programmatic upload from within the notebook to be uploaded but ran into the following exception/stacktrace: 
``` python
     1 try:
      2     this_notebook_path = PAPERMILL_OUTPUT_PATH
----> 3     neptune_notebooks.sync.sync('andrewannex/baryte', this_notebook_path)
      4 except NameError as ke:
      5     print('Papermill output path undefined, will not upload notebook')

~/code/anaconda3/envs/baryte_two/lib/python3.7/site-packages/neptune_notebooks/sync.py in sync(project_name, path, update_flag, new_flag)
     29     absolute_path = os.path.abspath(path)
     30     project = neptune.init(project_qualified_name=project_name)
---> 31     notebook_json = load_notebook_json(path)
     32     nbformat = int(notebook_json["nbformat"]) if "nbformat" in notebook_json else 0
     33 

~/code/anaconda3/envs/baryte_two/lib/python3.7/site-packages/neptune_notebooks/sync.py in load_notebook_json(path)
     72 def load_notebook_json(path):
     73     with open(path) as f:
---> 74         return json.load(f)
     75 
     76 

~/code/anaconda3/envs/baryte_two/lib/python3.7/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    291     kwarg; otherwise ``JSONDecoder`` is used.
    292     """
--> 293     return loads(fp.read(),
    294         cls=cls, object_hook=object_hook,
    295         parse_float=parse_float, parse_int=parse_int,

~/code/anaconda3/envs/baryte_two/lib/python3.7/encodings/ascii.py in decode(self, input, final)
     24 class IncrementalDecoder(codecs.IncrementalDecoder):
     25     def decode(self, input, final=False):
---> 26         return codecs.ascii_decode(input, self.errors)[0]
     27 
     28 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10635: ordinal not in range(128)
```
After the program exited, I was able to upload the notebook from python using the sync function, so my guess is that I ran into some sort of race condition (again I want the running notebook to upload itself). I think that the `errors` kwarg for `open` could allow for some attempts to correct/ignore errors like this, but I also see how what I am doing is highly non-standard.

I believe with my batch jobs I should be able to just use the command line call above after the papermill process exits, but I was hoping to make use of incremental checkpoint updates for long running jobs.

I also do not see the experiment associated with the notebook in the neptune web UI after running the sync command, I am still using the old api but updated to the newest versions of neptune client, and I didn't see a way to do so from the sync command.

**Comment by PiotrJander** [comment]
Hi @AndrewAnnex - now I see that your use case is about programmatically uploading a notebook from within itself.

I'm not an expert on how saving / updating notebooks work under the hood, but like you said, it might be some sort of a race condition.

But your use case definitely looks valid, so I'll flag this as a possible feature that our team should research @Herudaio .

>I also do not see the experiment associated with the notebook in the neptune web UI after running the sync command

Just bear in mind that in Neptune, notebooks are associated with projects, not with individual experiments (even though they can be browsed from the experiment view). So you need to make sure to create your experiments independently with `create_experiment` method (or `init` in the new Python interface).

I hope this is useful!

**Comment by AndrewAnnex** [comment]
thanks @PiotrJander, I'll take a look at how I am using experiments and my use of the python api/papermill. Currently I just use one project to capture multiple experiments over different independent datasets run through the same notebook "template" using papermill. Since the datasets aren't intended to be inter-compared, it may be better to use multiple projects each running experiments from the same notebook "template" for a single dataset that gets updated through time. That way each experiment in the project could use the same notebook file. 

In any case, I think my questions are fully answered, I'll close the issue for now. thanks again! -Andrew
