### ISSUE TITLE
Feature request: load API token from the Jupyter server

### ISSUE THREAD

**Issue by vmarkovtsev** [neptune-ai/neptune-notebooks#30]
### What I want

Not having to enter the API key for every new notebook. This critically complicates the usage of the "magic button" in a team of 10 people with Jupyter in Kubernetes (read: they refuse to participate in the mess).

### What I suggest

Provide a way to retrieve the API key from the Jupyter server. It could be loaded from `NEPTUNE_API_TOKEN` environment variable defined by Helm, from the FS or through LDAP or whatever else.
Currently, it is loaded from the browser local storage only.

### My workaround

I hack my Dockerfile to load the API key when Jupyter starts and insert it at
https://github.com/neptune-ml/neptune-notebooks/blob/master/packages/nbextension/neptune-notebook.js#L451 instead of the empty default `''`. I overwrite the JS file, which is soooo hacky.

**Comment by kamil-kaczmarek** [comment]
Hi @vmarkovtsev 

Thanks for this one.

Similarly to #31 we need to look closer, and - just like in #31 I'll get back to you soon with more details :slightly_smiling_face: 

Best,
Kamil

**Comment by pitercl** [comment]
Hi @vmarkovtsev,

I'd like to understand your use-case better. From what you wrote, I assume the following:
  - you're running a single Jupyter server per person (so the token would not actually be shared among multiple users)
  - the domain under which you run your Jupyter server changes frequently, e.g. with each pod/service restart (that's why the keeping the token in local storage is not good enough)

Is that correct or am I missing something?

**Comment by vmarkovtsev** [comment]
The token is the same for all the users.

I checked that the local storage did not preserve for the localhost for each new notebook. Probably, it should preserve for a specific domain, IDK - I am not a webdev expert.
However, I have to explain to the users that they need to copy-paste some token to their browsers. Besides, we get new users every month, the old users change laptops, etc. Our infra team is particularly not happy with exposing the API token directly. They would rather build it inside their Helm chart. My goal is to have a button which the users click every once in a while, without even knowing that there is such a thing like an API token or an integration.

**Comment by pitercl** [comment]
Thanks for your response, @vmarkovtsev .

Could you please explain why you're sharing a single API Token amongst multiple users? API Token is a password-like secret - it can be used to gain access to token's owner account.

By "users" do you mean your team members or users of your service?

As for persisting API Token across sessions on localhost - I checked it too and it works (although, you need to remember that port is part of the address that the storage is bound to, so, localhost:8888 and localhost:9999 don't share local  storages).

In general, our idea for Notebooks in Neptune is to provide a place for data scientists to keep track of their work. If you have a different use-case, we'd certainly be glad to hear it :smile: 

Best,
Piotr

**Comment by vmarkovtsev** [comment]
> Could you please explain why you're sharing a single API Token amongst multiple users?

I don't know :D I thought there was a bijection \<project\> - \<API key\>. Anyway, having individual tokens for each user will complicate my devops life further: we delegate all the auth and credentials to GitHub.

> By "users" do you mean your team members or users of your service?

The team members.

My current use case is increasing the transparency over the ongoing R&D which happens in Jupyter notebooks for all the team, including myself. The end-user overhead must be as low as possible. Ideally, zero (the sync button auto-clicks itself, the settings are embedded into Helm and Docker).

**Comment by pitercl** [comment]
Ok, thanks! So your use-case is exactly why we're doing it :smile: 

As for our API Tokens, the bijection is between users and tokens, so they shouldn't really be shared. It's actually part of the value given to our users - when you upload a notebook checkpoint, you do so as yourself. And, to be honest, I always thought, that keeping the token in local storage would be quite user-friendly - if the tokens disappear between sessions for Jupyter notebook hosted on the same domain (and port), please let me know - this would be a bug.

We're currently working on some improvements to the workflow with the extension - experiments will be associated with particular checkpoints, not entire notebooks, and those checkpoints will be uploaded automatically, without user's action when the experiment begins.

Does this help?

**Comment by vmarkovtsev** [comment]
All right, then the whole thing goes completely out of our devops control. I guess the GitHub auth integration would solve my problem, but it does not exist atm. There could also be a browser extension to automatically fill the token.

The original issue still makes sense for single-user environments which mix local and remote notebooks at random URLs.

**Comment by habemus-papadum** [comment]
In my dev workflow, I run will launch any number of local servers, each will grab a port near 8888 -- hence local storage is  not ideal; I am constantly having to enter the key (though honestly it seems more often that can be explained by just port changes.)  Would it be possible to create some (simple) chrome plugin that users could use to cache their api key -- i think this would still preserve your value proposition.  Or since my google account is already tied to neptune, maybe there is a way to use my google creds cached on the browser to pull the api key (the connect dialog would have a "use google" button)

**Comment by pitercl** [comment]
Hi @habemus-papadum, such extension was actually created by @vmarkovtsev, but I'm not sure it works with the updated version of our extension.

I've passed your feedback to our product team and we'll keep it in mind. Thanks!

Btw, if you discover that API token disappears from your local storage in some cases, we'd love to know - this would be a bug :)

**Comment by ljburtz** [comment]
Any update on this to avoid manually pasting the token in the notebook? 
Thanks!

**Comment by Herudaio** [comment]
Hi @ljburtz! 
Unfortunately, the only way currently to pass the token to the extension is by pasting it in the UI.
Would you mind telling me what's your workflow? As the token is stored in the local cache typically it is only needed to input it once.

**Comment by ljburtz** [comment]
I've now understood and tested that the token persists in the browser's local cache and is already pre-input even when the docker container that is running the jupyter server is restarted. That satisfies my workflow. Thank you for this.
