### ISSUE TITLE
Feature request: automatic integration

### ISSUE THREAD

**Issue by vmarkovtsev** [neptune-ai/neptune-notebooks#31]
### What I want

Not having to integrate every new notebook.

### My suggestion

Add a setting to automatically integrate the notebook with Neptune at startup.

### My current workaround

No workaround yet. I have to hack some JS in https://github.com/neptune-ml/neptune-notebooks/blob/master/packages/nbextension/neptune-notebook.js to automatically call `createNotebook` together with #30

**Comment by kamil-kaczmarek** [comment]
Hi @vmarkovtsev 

Thanks for this suggestion. We'll take a closer look how we can introduce automatic integration.
I'll get back to you soon with more details.

Best,
Kamil

**Comment by pitercl** [comment]
Hi @vmarkovtsev, 

The reason behind not having this implemented in the first place was that kernel and notebook are not exactly 1 to 1. In particular, you can have multiple notebooks connected to a single kernel (and Jupyter Lab makes this fairly easy).

Anyway, I'll take a look and get back to you.
